name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CACHE_VERSION: 1
  DEFAULT_PYTHON: "3.11"
  PRE_COMMIT_CACHE: ~/.cache/pre-commit

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  prepare-base:
    name: Prepare base dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4.1.2

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          check-latest: true

      - name: Create Python virtual environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          pip install pre-commit python-pylint

      - name: Run pylint
        run: |
          pylint **/*.py

      - name: GitHub Action for pylint
        uses: cclauss/GitHub-Action-for-pylint@06.0
        with:
          args: 'pylint'
